export type WaitingRoomState = "NOT_ARRIVED" | "VISITOR_WAITING" | "PRISONER_WAITING" | "BOTH_PRESENT" | "TECHNICAL_ISSUE" | "STAFF_REVIEW" | "READY_TO_START" | "LATE" | "LIVE" | "CANCELLED";

const transitions: Record<WaitingRoomState, readonly WaitingRoomState[]> = {
  NOT_ARRIVED: ["NOT_ARRIVED", "VISITOR_WAITING", "PRISONER_WAITING", "LATE", "STAFF_REVIEW", "CANCELLED"],
  VISITOR_WAITING: ["VISITOR_WAITING", "BOTH_PRESENT", "TECHNICAL_ISSUE", "STAFF_REVIEW", "READY_TO_START", "LATE", "CANCELLED"],
  PRISONER_WAITING: ["PRISONER_WAITING", "BOTH_PRESENT", "TECHNICAL_ISSUE", "STAFF_REVIEW", "READY_TO_START", "LATE", "CANCELLED"],
  BOTH_PRESENT: ["BOTH_PRESENT", "READY_TO_START", "TECHNICAL_ISSUE", "STAFF_REVIEW", "CANCELLED"],
  TECHNICAL_ISSUE: ["TECHNICAL_ISSUE", "READY_TO_START", "STAFF_REVIEW", "CANCELLED"],
  STAFF_REVIEW: ["STAFF_REVIEW", "READY_TO_START", "TECHNICAL_ISSUE", "CANCELLED"],
  READY_TO_START: ["READY_TO_START", "LIVE", "STAFF_REVIEW", "CANCELLED"],
  LATE: ["LATE", "VISITOR_WAITING", "STAFF_REVIEW", "CANCELLED"],
  LIVE: ["LIVE"],
  CANCELLED: ["CANCELLED"],
};

export function canTransitionWaitingRoom(from: string, to: string): boolean {
  return (transitions[from as WaitingRoomState] || []).includes(to as WaitingRoomState);
}
