import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("staff and provider joins preserve facility integrity", async () => {
  const controlAppointments = await readFile(new URL("../lib/server/control-appointments.ts", import.meta.url), "utf8");
  const controlAppointmentRoute = await readFile(new URL("../app/api/control/appointments/route.ts", import.meta.url), "utf8");
  const appointmentDecisions = await readFile(new URL("../lib/server/appointment-decisions.ts", import.meta.url), "utf8");
  const waitingRoom = await readFile(new URL("../app/api/control/waiting-room/route.ts", import.meta.url), "utf8");
  const verification = await readFile(new URL("../app/api/control/verification/route.ts", import.meta.url), "utf8");
  const evidence = await readFile(new URL("../app/api/control/verification/evidence/[documentId]/route.ts", import.meta.url), "utf8");
  const controlLiveSessions = await readFile(new URL("../app/api/control/live-sessions/route.ts", import.meta.url), "utf8");
  const kioskLiveSession = await readFile(new URL("../app/api/kiosk/visits/[visitId]/live-session/route.ts", import.meta.url), "utf8");
  const kioskPresence = await readFile(new URL("../app/api/kiosk/visits/[visitId]/presence/route.ts", import.meta.url), "utf8");
  const kioskDeviceCheck = await readFile(new URL("../app/api/kiosk/visits/[visitId]/device-check/route.ts", import.meta.url), "utf8");
  const incidents = await readFile(new URL("../app/api/control/incidents/route.ts", import.meta.url), "utf8");
  const liveKit = await readFile(new URL("../app/api/webhooks/livekit/route.ts", import.meta.url), "utf8");
  const resources = await readFile(new URL("../lib/server/resources.ts", import.meta.url), "utf8");

  assert.match(controlAppointments, /p\.id = a\.prisoner_id AND p\.facility_id = a\.facility_id/);
  assert.match(controlAppointmentRoute, /p\.id = a\.prisoner_id AND p\.facility_id = a\.facility_id/);
  assert.match(appointmentDecisions, /p\.id = a\.prisoner_id AND p\.facility_id = a\.facility_id/);
  assert.match(waitingRoom, /p\.id = a\.prisoner_id AND p\.facility_id = a\.facility_id/);
  assert.match(verification, /vr\.id = vc\.relationship_id AND vr\.facility_id = vc\.facility_id/);
  assert.match(verification, /u\.id = vr\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  assert.match(verification, /p\.id = vr\.prisoner_id AND p\.facility_id = vr\.facility_id/);
  assert.match(evidence, /vc\.id = ed\.verification_case_id AND vc\.facility_id = ed\.facility_id/);
  assert.match(liveKit, /a\.id = vs\.appointment_id AND a\.facility_id = vs\.facility_id/);
  assert.match(kioskLiveSession, /a\.id = vs\.appointment_id AND a\.facility_id = vs\.facility_id/);
  assert.match(resources, /r\.id = rr\.resource_id AND r\.facility_id = rr\.facility_id/);
  assert.match(controlAppointments, /r\.id = rr\.resource_id AND r\.facility_id = rr\.facility_id/);
  assert.match(controlAppointmentRoute, /r\.id = rr\.resource_id AND r\.facility_id = rr\.facility_id/);
  assert.match(controlAppointments, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  const appointmentRoute = await readFile(new URL("../app/api/control/appointments/route.ts", import.meta.url), "utf8");
  assert.match(appointmentRoute, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  assert.match(waitingRoom, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  assert.match(controlLiveSessions, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  assert.match(kioskLiveSession, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  assert.match(kioskPresence, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  assert.match(kioskDeviceCheck, /u\.id = a\.visitor_user_id AND u\.user_type = 'VISITOR'/);
  const videoSession = await readFile(new URL("../lib/server/video/session.ts", import.meta.url), "utf8");
  assert.match(videoSession, /a\.id = vs\.appointment_id AND a\.facility_id = vs\.facility_id/);
  assert.match(incidents, /reporter\.id = i\.reporter_user_id AND reporter\.user_type = 'STAFF'/);
  assert.match(incidents, /assignee\.id = i\.assigned_user_id AND assignee\.user_type = 'STAFF'/);
  assert.match(incidents, /FROM appointments WHERE id = \? AND facility_id = \?/);
  assert.match(incidents, /FROM visit_sessions WHERE id = \? AND facility_id = \?/);
  assert.match(incidents, /FROM resources WHERE id = \? AND facility_id = \?/);
});
